[package]
name = "discord_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.11.7", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "utils", "builder", "cache"] }
tokio = { version = "1", features = ["full"] }

